package com.palette.busi.project.tms.core.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.annotations.ResultType;

import com.palette.busi.project.tms.core.entity.TmConsignment;
import com.palette.busi.project.tms.core.dao.TmConsignmentSqlProvider;
import com.palette.busi.project.tms.core.base.BaseMybatisMapper;

public interface TmConsignmentIntf extends BaseMybatisMapper {


	@Select("SELECT  TM_CONSIGNMENT_ID  AS tmConsignmentId, CONSIGNMENT_NO  AS consignmentNo, MEMBER_CODE  AS memberCode, IDCARD_NO  AS idcardNo, IDCARD_FULL_NAME  AS idcardFullName, IDCARD_ADDRESS  AS idcardAddress, IDCARD_FRONT_IMG  AS idcardFrontImg, IDCARD_BACK_IMG  AS idcardBackImg, SHIPPER_MEMBER_CODE  AS shipperMemberCode, SHIPPER_NAME  AS shipperName, SHIPPER_COMPANY_NAME  AS shipperCompanyName, SHIPPER_COUNTRY_CODE  AS shipperCountryCode, SHIPPER_STATE_CODE  AS shipperStateCode, SHIPPER_CITY_CODE  AS shipperCityCode, SHIPPER_POST_CODE  AS shipperPostCode, SHIPPER_STREET  AS shipperStreet, SHIPPER_MOBILE_NO  AS shipperMobileNo, SHIPPER_PHONE_NO  AS shipperPhoneNo, SHIPPER_OTHER_CONTACT_NO  AS shipperOtherContactNo, SHIPPER_CHINESE_FULL_ADDRESS  AS shipperChineseFullAddress, SHIPPER_ENGLISH_FULL_ADDRESS  AS shipperEnglishFullAddress, CONSIGNEE_NAME  AS consigneeName, CONSIGNEE_COMPANY_NAME  AS consigneeCompanyName, CONSIGNEE_COUNTRY_CODE  AS consigneeCountryCode, CONSIGNEE_STATE_NAME  AS consigneeStateName, CONSIGNEE_STATE_CODE  AS consigneeStateCode, CONSIGNEE_CITY_NAME  AS consigneeCityName, CONSIGNEE_CITY_CODE  AS consigneeCityCode, CONSIGNEE_DISTRICT_NAME  AS consigneeDistrictName, CONSIGNEE_DISTRICT_CODE  AS consigneeDistrictCode, CONSIGNEE_POST_CODE  AS consigneePostCode, CONSIGNEE_STREET  AS consigneeStreet, CONSIGNEE_MOBILE_NO  AS consigneeMobileNo, CONSIGNEE_PHONE_NO  AS consigneePhoneNo, CONSIGNEE_OTHER_CONTACT_NO  AS consigneeOtherContactNo, CONSIGNEE_CHINESE_FULL_ADDRESS  AS consigneeChineseFullAddress, CONSIGNEE_ENGLISH_FULL_ADDRESS  AS consigneeEnglishFullAddress, TOTAL_GOODS_DESCRIPTION  AS totalGoodsDescription, TOTAL_GOODS_BRAND  AS totalGoodsBrand, TOTAL_GOODS_SPEC  AS totalGoodsSpec, TOTAL_GOODS_UNIT  AS totalGoodsUnit, TOTAL_GOODS_VALUE  AS totalGoodsValue, TOTAL_GOODS_VALUE_CURRENCY  AS totalGoodsValueCurrency, TOTAL_QTY  AS totalQty, TOTAL_WEIGHT  AS totalWeight, SELLER_NAME  AS sellerName, SELLER_ORDER_NO  AS sellerOrderNo, LOGISTICS_VENDOR  AS logisticsVendor, LOGISTICS_NO  AS logisticsNo, WAREHOUSE_CODE  AS warehouseCode, TRANSFER_TYPE  AS transferType, MEMO  AS memo, CREATE_TIME  AS createTime, PRINCIPLE  AS principle, MCT_API_REQUEST_ID  AS mctApiRequestId, SOURCE_REQUEST_ID  AS sourceRequestId, DATA_SOURCE  AS dataSource, SERVICE_PRODUCT_CODE  AS serviceProductCode, RECORD_VERSION  AS recordVersion, COMPANY_CODE  AS companyCode, CREATE_USER_CODE  AS createUserCode, CREATE_DATE_TIME  AS createDateTime, UPDATE_USER_CODE  AS updateUserCode, UPDATE_DATE_TIME  AS updateDateTime FROM tm_consignment WHERE tm_consignment_id=#{tmConsignmentId}")
	public TmConsignment selectTmConsignmentById(@Param("tmConsignmentId") int tmConsignmentId);
	
	@Select("SELECT  TM_CONSIGNMENT_ID  AS tmConsignmentId, CONSIGNMENT_NO  AS consignmentNo, MEMBER_CODE  AS memberCode, IDCARD_NO  AS idcardNo, IDCARD_FULL_NAME  AS idcardFullName, IDCARD_ADDRESS  AS idcardAddress, IDCARD_FRONT_IMG  AS idcardFrontImg, IDCARD_BACK_IMG  AS idcardBackImg, SHIPPER_MEMBER_CODE  AS shipperMemberCode, SHIPPER_NAME  AS shipperName, SHIPPER_COMPANY_NAME  AS shipperCompanyName, SHIPPER_COUNTRY_CODE  AS shipperCountryCode, SHIPPER_STATE_CODE  AS shipperStateCode, SHIPPER_CITY_CODE  AS shipperCityCode, SHIPPER_POST_CODE  AS shipperPostCode, SHIPPER_STREET  AS shipperStreet, SHIPPER_MOBILE_NO  AS shipperMobileNo, SHIPPER_PHONE_NO  AS shipperPhoneNo, SHIPPER_OTHER_CONTACT_NO  AS shipperOtherContactNo, SHIPPER_CHINESE_FULL_ADDRESS  AS shipperChineseFullAddress, SHIPPER_ENGLISH_FULL_ADDRESS  AS shipperEnglishFullAddress, CONSIGNEE_NAME  AS consigneeName, CONSIGNEE_COMPANY_NAME  AS consigneeCompanyName, CONSIGNEE_COUNTRY_CODE  AS consigneeCountryCode, CONSIGNEE_STATE_NAME  AS consigneeStateName, CONSIGNEE_STATE_CODE  AS consigneeStateCode, CONSIGNEE_CITY_NAME  AS consigneeCityName, CONSIGNEE_CITY_CODE  AS consigneeCityCode, CONSIGNEE_DISTRICT_NAME  AS consigneeDistrictName, CONSIGNEE_DISTRICT_CODE  AS consigneeDistrictCode, CONSIGNEE_POST_CODE  AS consigneePostCode, CONSIGNEE_STREET  AS consigneeStreet, CONSIGNEE_MOBILE_NO  AS consigneeMobileNo, CONSIGNEE_PHONE_NO  AS consigneePhoneNo, CONSIGNEE_OTHER_CONTACT_NO  AS consigneeOtherContactNo, CONSIGNEE_CHINESE_FULL_ADDRESS  AS consigneeChineseFullAddress, CONSIGNEE_ENGLISH_FULL_ADDRESS  AS consigneeEnglishFullAddress, TOTAL_GOODS_DESCRIPTION  AS totalGoodsDescription, TOTAL_GOODS_BRAND  AS totalGoodsBrand, TOTAL_GOODS_SPEC  AS totalGoodsSpec, TOTAL_GOODS_UNIT  AS totalGoodsUnit, TOTAL_GOODS_VALUE  AS totalGoodsValue, TOTAL_GOODS_VALUE_CURRENCY  AS totalGoodsValueCurrency, TOTAL_QTY  AS totalQty, TOTAL_WEIGHT  AS totalWeight, SELLER_NAME  AS sellerName, SELLER_ORDER_NO  AS sellerOrderNo, LOGISTICS_VENDOR  AS logisticsVendor, LOGISTICS_NO  AS logisticsNo, WAREHOUSE_CODE  AS warehouseCode, TRANSFER_TYPE  AS transferType, MEMO  AS memo, CREATE_TIME  AS createTime, PRINCIPLE  AS principle, MCT_API_REQUEST_ID  AS mctApiRequestId, SOURCE_REQUEST_ID  AS sourceRequestId, DATA_SOURCE  AS dataSource, SERVICE_PRODUCT_CODE  AS serviceProductCode, RECORD_VERSION  AS recordVersion, COMPANY_CODE  AS companyCode, CREATE_USER_CODE  AS createUserCode, CREATE_DATE_TIME  AS createDateTime, UPDATE_USER_CODE  AS updateUserCode, UPDATE_DATE_TIME  AS updateDateTime FROM tm_consignment")
	public List<TmConsignment> selectAllTmConsignment();
	
	@Insert("insert into tm_consignment ( TM_CONSIGNMENT_ID, CONSIGNMENT_NO, MEMBER_CODE, IDCARD_NO, IDCARD_FULL_NAME, IDCARD_ADDRESS, IDCARD_FRONT_IMG, IDCARD_BACK_IMG, SHIPPER_MEMBER_CODE, SHIPPER_NAME, SHIPPER_COMPANY_NAME, SHIPPER_COUNTRY_CODE, SHIPPER_STATE_CODE, SHIPPER_CITY_CODE, SHIPPER_POST_CODE, SHIPPER_STREET, SHIPPER_MOBILE_NO, SHIPPER_PHONE_NO, SHIPPER_OTHER_CONTACT_NO, SHIPPER_CHINESE_FULL_ADDRESS, SHIPPER_ENGLISH_FULL_ADDRESS, CONSIGNEE_NAME, CONSIGNEE_COMPANY_NAME, CONSIGNEE_COUNTRY_CODE, CONSIGNEE_STATE_NAME, CONSIGNEE_STATE_CODE, CONSIGNEE_CITY_NAME, CONSIGNEE_CITY_CODE, CONSIGNEE_DISTRICT_NAME, CONSIGNEE_DISTRICT_CODE, CONSIGNEE_POST_CODE, CONSIGNEE_STREET, CONSIGNEE_MOBILE_NO, CONSIGNEE_PHONE_NO, CONSIGNEE_OTHER_CONTACT_NO, CONSIGNEE_CHINESE_FULL_ADDRESS, CONSIGNEE_ENGLISH_FULL_ADDRESS, TOTAL_GOODS_DESCRIPTION, TOTAL_GOODS_BRAND, TOTAL_GOODS_SPEC, TOTAL_GOODS_UNIT, TOTAL_GOODS_VALUE, TOTAL_GOODS_VALUE_CURRENCY, TOTAL_QTY, TOTAL_WEIGHT, SELLER_NAME, SELLER_ORDER_NO, LOGISTICS_VENDOR, LOGISTICS_NO, WAREHOUSE_CODE, TRANSFER_TYPE, MEMO, CREATE_TIME, PRINCIPLE, MCT_API_REQUEST_ID, SOURCE_REQUEST_ID, DATA_SOURCE, SERVICE_PRODUCT_CODE, RECORD_VERSION, COMPANY_CODE, CREATE_USER_CODE, CREATE_DATE_TIME, UPDATE_USER_CODE, UPDATE_DATE_TIME ) values (#{tmConsignmentId},#{consignmentNo},#{memberCode},#{idcardNo},#{idcardFullName},#{idcardAddress},#{idcardFrontImg},#{idcardBackImg},#{shipperMemberCode},#{shipperName},#{shipperCompanyName},#{shipperCountryCode},#{shipperStateCode},#{shipperCityCode},#{shipperPostCode},#{shipperStreet},#{shipperMobileNo},#{shipperPhoneNo},#{shipperOtherContactNo},#{shipperChineseFullAddress},#{shipperEnglishFullAddress},#{consigneeName},#{consigneeCompanyName},#{consigneeCountryCode},#{consigneeStateName},#{consigneeStateCode},#{consigneeCityName},#{consigneeCityCode},#{consigneeDistrictName},#{consigneeDistrictCode},#{consigneePostCode},#{consigneeStreet},#{consigneeMobileNo},#{consigneePhoneNo},#{consigneeOtherContactNo},#{consigneeChineseFullAddress},#{consigneeEnglishFullAddress},#{totalGoodsDescription},#{totalGoodsBrand},#{totalGoodsSpec},#{totalGoodsUnit},#{totalGoodsValue},#{totalGoodsValueCurrency},#{totalQty},#{totalWeight},#{sellerName},#{sellerOrderNo},#{logisticsVendor},#{logisticsNo},#{warehouseCode},#{transferType},#{memo},#{createTime},#{principle},#{mctApiRequestId},#{sourceRequestId},#{dataSource},#{serviceProductCode},#{recordVersion},#{companyCode},#{createUserCode},#{createDateTime},#{updateUserCode},#{updateDateTime})")
	public int insertTmConsignment(TmConsignment tmConsignment);

	@UpdateProvider(type=TmConsignmentSqlProvider.class, method="update")
	public int updateTmConsignment(TmConsignment tmConsignment);
	
	@Delete("delete from tm_consignment where tm_consignment_id = #{tmConsignmentId}")
	public int deleteTmConsignment(@Param("tmConsignmentId") int tmConsignmentId);

    @SelectProvider(type=TmConsignmentSqlProvider.class, method="selectAllByRecord")
    @ResultType(TmConsignment.class)
    public List<TmConsignment> selectAllByRecord(TmConsignment record);
    
}